# Generated by Django 3.1.3 on 2020-11-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201105_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Darowizna', 'verbose_name_plural': 'Darowizny'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Fundacja', 'verbose_name_plural': 'Fundacje'},
        ),
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
